name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      DATADOG_API_KEY: "asdf"
      DATADOG_APP_KEY: "hjkl"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      #   - name: Set Datadog API Key
      #     run: echo "::set-env name=TF_VAR_datadog_api_key::${{ secrets.DATADOG_API_KEY }}"

      - name: Initialize Terraform
        run: terraform init

      - name: Terraform plan
        run: terraform plan -out test
        env:
          TF_VAR_datadog_api_key: ${{ env.DATADOG_API_KEY }}
          TF_VAR_datadog_app_key: ${{ env.DATADOG_APP_KEY }}

      - name: CAT
        run: cat test

    #   - name: Terraform apply
    #     run: terraform apply -auto-approve
